### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by xmzqhl** [thejinchao/dhexchange#1]
Hello,你好，看了您的代码和博客，觉得写得非常好，能否在博客中加上以下几个函数的计算过程：_u128_sub，_mulmodp，_powmodp_r，_powmodp。还有就是time_t seed; time(&seed)； srand((unsigned int)seed);这三行代码可以放到DH_generate_key_pair函数的内部，就不用外部每次调用时自己去写。如果能解说一下 128位的数字a的b次方模P的计算过程，就万分感谢了！

**Comment by thejinchao** [comment]
谢谢关注，这段代码里的算法是抄的云风的skynet里的代码
https://github.com/thejinchao/dhexchange/blob/master/dhexchange.c
具体原理我当时研究过，现在记不清了，大概就是一个简单的大数算法，如果有空的话我会去解释一下。
至于初始化随机数种子一般来说是不会放到函数内部的，这不是功能函数应该做的事情。
